[settings]
experimental = true

[tools]
"github:JohnnyMorganz/StyLua" = "latest"
"github:JohnnyMorganz/luau-lsp" = "latest"
"github:Kampfkarren/selene" = "latest"

[tasks.test]
description = "Test pathfs"
run = "lune run test"
