name = "jiwonz/pathfs"
version = "0.6.0-rc.8"
description = "luau-path + @lune/fs and some utilities"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/lune-pathfs"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[engines]
lune = "^0.9.4"
pesde = "^0.7.0-rc.1"

[dependencies]
luau_path = { name = "jiwonz/luau_path", version = "^0.1.4", target = "luau" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }
